export enum STATUSEVENTS{
    CREATED = 'CREATED',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED'
}

export enum CATEGORY {
    CITA = 'CITA_MEDICA',
    PRACTICA = 'PRACTICA',
    CLASE = 'CLASE',
    RECORDATORIO = 'RECORDATORIO'
}